[project]
name = "fastapi-blog-async"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rahul M U", email = "rmuwork51@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
fastapi-blog-async = "fastapi_blog_async:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
